### PR TITLE
Add bitvec dependencies for major optimisations of binary fields

### PR DESCRIPTION
**Pull request by Multramate**
### Pull Request Checklist

- [x] Update [ChangeLog.md](https://github.com/adjoint-io/galois-field/blob/master/ChangeLog.md)
- [x] Tests are passing.
- [x] Benchmarks are not regressing.

### CODE REVIEW

**Comment by Multramate** [comment]
Awaiting the newest release of bitvec.

**Comment by Bodigrim** [comment]
[`bitvec-1.0.2.0`](http://hackage.haskell.org/package/bitvec-1.0.2.0) has been just released.

**Comment by Multramate** [comment]
This is ready to review.

**Comment by Multramate** [comment]
This addresses #19 as well.

**Pull request merged**
